basePath: /api/v1
definitions:
  models.Constellation:
    properties:
      constellation_id:
        type: integer
      constellation_name:
        type: string
      region_id:
        type: integer
    type: object
  models.Planet:
    properties:
      asteroid_belt_count:
        type: integer
      moon_count:
        type: integer
      planet_id:
        type: integer
      planet_name:
        type: string
      system_id:
        type: integer
      type:
        type: string
    type: object
  models.Region:
    properties:
      region_id:
        type: integer
      region_name:
        type: string
    type: object
  models.SpectralClassCount:
    properties:
      spectral_class:
        type: string
      system_count:
        type: integer
    type: object
  models.Stargate:
    properties:
      destination_stargate_id:
        type: integer
      destination_system_id:
        type: integer
      stargate_id:
        type: integer
      stargate_name:
        type: string
      system_id:
        type: integer
    type: object
  models.Station:
    properties:
      station_id:
        type: integer
      station_name:
        type: string
      system_id:
        type: integer
    type: object
  models.System:
    properties:
      constellation_id:
        type: integer
      security_class:
        description: Use pointer for nullable string
        type: string
      security_status:
        type: number
      spectral_class:
        description: Use pointer for nullable string
        type: string
      system_id:
        type: integer
      system_name:
        type: string
      x_pos:
        type: number
      y_pos:
        type: number
      z_pos:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for the Astrocartics application.
  title: Astrocartics API
  version: "1.0"
paths:
  /constellations:
    get:
      consumes:
      - application/json
      description: Get all constellations, or search for a constellation by name
      parameters:
      - description: Constellation name to search for
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Constellation'
            type: array
      summary: Get constellations
      tags:
      - constellations
  /constellations/{constellationID}:
    get:
      consumes:
      - application/json
      description: Get a single constellation by its unique ID
      parameters:
      - description: Constellation ID
        in: path
        name: constellationID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Constellation'
            type: array
      summary: Get a constellation by ID
      tags:
      - constellations
  /constellations/{constellationID}/systems:
    get:
      consumes:
      - application/json
      description: Get all systems for a specific constellation
      parameters:
      - description: Constellation ID
        in: path
        name: constellationID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.System'
            type: array
      summary: Get systems by constellation ID
      tags:
      - systems
  /planets:
    get:
      consumes:
      - application/json
      description: Get all planets, or search for a planet by name
      parameters:
      - description: Planet name to search for
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Planet'
            type: array
      summary: Get planets
      tags:
      - planets
  /planets/{planetID}:
    get:
      consumes:
      - application/json
      description: Get a single planet by its unique ID
      parameters:
      - description: Planet ID
        in: path
        name: planetID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Planet'
      summary: Get a planet by ID
      tags:
      - planets
  /regions:
    get:
      consumes:
      - application/json
      description: Get all regions, or search for a region by name
      parameters:
      - description: Region name to search for
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Region'
            type: array
      summary: Get regions
      tags:
      - regions
  /regions/{regionID}:
    get:
      consumes:
      - application/json
      description: Get a single region by its unique ID
      parameters:
      - description: Region ID
        in: path
        name: regionID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Region'
      summary: Get a region by ID
      tags:
      - regions
  /regions/{regionID}/constellations:
    get:
      consumes:
      - application/json
      description: Get all constellations for a specific region
      parameters:
      - description: Region ID
        in: path
        name: regionID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Constellation'
            type: array
      summary: Get constellations by region ID
      tags:
      - constellations
  /regions/{regionID}/systems:
    get:
      consumes:
      - application/json
      description: Get all systems for a specific region
      parameters:
      - description: Region ID
        in: path
        name: regionID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.System'
            type: array
      summary: Get systems by region ID
      tags:
      - systems
  /reports/spectral-class-counts:
    get:
      consumes:
      - application/json
      description: Get a report of system counts by spectral class
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SpectralClassCount'
            type: array
      summary: Get spectral class counts
      tags:
      - reports
  /stargates:
    get:
      consumes:
      - application/json
      description: Get all stargates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Stargate'
            type: array
      summary: Get stargates
      tags:
      - stargates
  /stations:
    get:
      consumes:
      - application/json
      description: Get all stations, or search for a station by name
      parameters:
      - description: Station name to search for
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Station'
            type: array
      summary: Get stations
      tags:
      - stations
  /stations/{stationID}:
    get:
      consumes:
      - application/json
      description: Get a single station by its unique ID
      parameters:
      - description: Station ID
        in: path
        name: stationID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Station'
      summary: Get a station by ID
      tags:
      - stations
  /systems:
    get:
      consumes:
      - application/json
      description: Get all systems, or search for a system by name
      parameters:
      - description: System name to search for
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.System'
            type: array
      summary: Get systems
      tags:
      - systems
  /systems/{systemID}:
    get:
      consumes:
      - application/json
      description: Get a single system by its unique ID
      parameters:
      - description: System ID
        in: path
        name: systemID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.System'
            type: array
      summary: Get a system by ID
      tags:
      - systems
  /systems/{systemID}/planets:
    get:
      consumes:
      - application/json
      description: Get all planets for a specific system
      parameters:
      - description: System ID
        in: path
        name: systemID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Planet'
            type: array
      summary: Get planets by system ID
      tags:
      - planets
  /systems/{systemID}/stargates:
    get:
      consumes:
      - application/json
      description: Get all stargates for a specific system
      parameters:
      - description: System ID
        in: path
        name: systemID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Stargate'
            type: array
      summary: Get stargates by system ID
      tags:
      - stargates
  /systems/{systemID}/stations:
    get:
      consumes:
      - application/json
      description: Get all stations for a specific system
      parameters:
      - description: System ID
        in: path
        name: systemID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Station'
            type: array
      summary: Get stations by system ID
      tags:
      - stations
swagger: "2.0"
